package com.example.acae30.modelos

data class DetallePedido(
    var Id: Int,//0
    var Id_pedido: Int?,//1
    var Id_producto: Int?,//2
    var Codigo: String?,//3
    var Descripcion: String?,//4
    var Costo: Float?,//5
    var Costo_iva: Float?,//6
    var Precio: Float?,//7
    var Precio_iva: Float?,//8
    var Precio_u: Float?,//9
    var Precio_u_iva: Float?,//10
    var Cantidad: Float?,//11
    var Precio_venta_siva: Float?,//12
    var Precio_venta: Float?,//13
    var Total: Float?,//14
    var Total_iva: Float?,//15
    var Unidad: String?,//16
    var Bonificado: Int?,//17
    var Descuento: Float?,//18
    var Precio_editado: String?,//19
    var Idunidad: Int?,//20
    var Codigo_de_barra: String?,//21
    var EquivaleUni: Float,//22
    var EquivaleFra: Float,//23
    var UniEquivale: String?,//24
    var Tipo: String,//25
    var IdMarca: Int?,//26
    var IdSku: Int?,//27
    var IdLinea: Int?,//28
    var IdSubLinea: Int?,//29
    var IdRubro: Int?,//30
    var IdProductor: Int?,//31
    var IdProveedor: Int?,//32
    var MetodoGestion: String,//33
    var TipoFiscal: String,//34
    var IdLote: Int?,//35
    var Lote: String?,//36
    var FechaVencimiento: String?,//37
    var IdBodega: Int?,//38
    var CodBodega: String?,//39
    var Bodega: String?//40
)