package com.example.acae30.listas

class InventarioRetrofit (
    val id : Int,
    val codigo : String,
    val codigo_de_barra : String? = "",
    val tipo : String,
    val descripcion : String,
    val unidad_medida : String? = "",
    val fraccion : Float? = 0f,
    val nombre_fraccion : String? = "",
    val costo : Float? = 0f,
    val costo_iva : Float? = 0f,
    val ult_costo : Float? = 0f,
    val ult_costo_iva : Float? = 0f,
    val existencia : Float? = 0f,
    val existencia_u : Float? = 0f,
    val precio : Float? = 0f,
    val precio_u : Float? = 0f,
    val precio_u_iva : Float? = 0f,
    val precio_iva : Float? = 0f,
    val bonificado : Float? = 0f,
    val lote : String? = "",
    val fecha_vencimiento : String? = "",
    val precio2 : Float? = 0f,
    val precio2_iva : Float? = 0f,
    val precio_u2 : Float? = 0f,
    val precio_u2_iva : Float? = 0f,
    val precio_viñeta : Float? = 0f,
    val precio_viñeta_iva : Float? = 0f,
)